source "https://rubygems.org"
git_source( :github ) { |repo| "https://github.com/#{repo}.git" }

# Ruby and rails versions:
ruby File.read( ".ruby-version" ).strip
gem "rails", "~> 7.0.4", ">= 7.0.4.3"

# Basic deps:
gem "api-versions", "~> 1.2"
gem "bootsnap", require: false
gem "kredis"
gem "rack-cors"
gem "redis", "~> 4.0"

# User login:
gem "bcrypt", "~> 3.1.7"
gem "jwt", "~> 2.3.0"

group :development, :test do
  # DB:
  gem "sqlite3", "~> 1.4"
  # Use Puma as the app server
  gem "puma", "~> 5.0"
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end

group :production do
  # DB
  gem "mysql2" 
  gem "passenger", ">= 5.0.25", require: "phusion_passenger/rack_handler"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [ :mingw, :mswin, :x64_mingw, :jruby ]

