version: '3.3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3337:3306'
    expose:
      # Opens port 3306 on the container
      - '3337'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  # TODO: replace with env to run ruby on rails 
  # backend:
  #   #image: php:8.1-cli
  #   build:
  #       context: ./
  #       dockerfile: ./php.Dockerfile
  #   restart: always
  #   working_dir: /app
  #   command: tail -F anything
  #   network_mode: "host"
  #   #environment:
  #     # MYSQL_DATABASE: 'db'
  #   volumes:
  #     - ../backend:/app

  webrtc-server:
    build:
        context: ./
        dockerfile: ./development/node.Dockerfile
    restart: always
    working_dir: /app
    command: tail -F anything
    network_mode: "host"
    volumes:
      - ../webrtc-server:/app

  frontend:
    build:
        context: ./
        dockerfile: ./development/node.Dockerfile
    restart: always
    working_dir: /app
    command: tail -F anything
    network_mode: "host"
    volumes:
      - ../frontend:/app

# Names our volume
volumes:
  my-db: